./parser 1.cmm
./parser 2.cmm
./parser 3.cmm
./parser 4.cmm
./parser 5.cmm
./parser 6.cmm
./parser 7.cmm
./parser 8.cmm
./parser 9.cmm
./parser 10.cmm
./parser 11.cmm
./parser 12.cmm
./parser 13.cmm
./parser 14.cmm
./parser 15.cmm
./parser 16.cmm
./parser 18.cmm
./parser 19.cmm